name: Create markdown files

on:
  push:
    branches: [ main ]
    paths: ['examples/**/**']

jobs:

  create_content_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create files
      id: create_files
      run: |
        if [ -d "/content" ]; then
          echo "Content folder exists."
        else
          mkdir -p content
        fi
        FOLDERS=$(ls -d examples/*/ | jq -R)
        for example_folder in $FOLDERS;
        do
          resource=$(cut -d "/" -f 2 <<< "$example_folder")
          filename=${resource}.md
          if [ -f "$filename" ]; then
            echo "$filename exists."
          else
            touch ./content/${filename}
            echo "$filename created."
          fi
        done

    - name: Commit and Push Changes
      run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "action@github.com"
            git pull origin main
            git add ./content/*
            git commit -m "Add markdown files"
            git push
          else
            echo "No changes!";
          fi